### ISSUE TITLE
Create normative references

### ISSUE THREAD

**Issue by milesmcc** [firstlookmedia/keylist-rfc#1]
Currently, the `back` section is empty and therefore doesn't contain normative references. We'll need to add those before we can submit. We will also want to generally just increase the density of citations.

**Comment by micahflee** [comment]
More information on what normative and informative references are:
https://www.ietf.org/blog/iesg-statement-normative-and-informative-references/

And the style guide for writing them:
https://tools.ietf.org/html/rfc7322#section-6

**Comment by milesmcc** [comment]
Marking as closed, because all the references are present at the moment as far as I can tell.
