### ISSUE TITLE
Keylist media type and syntax

### ISSUE THREAD

**Issue by ed-davies** [firstlookmedia/keylist-rfc#6]
The media type of the keylist should be specified. Presumably text/plain;charset='utf-8'.

In section 3.1:

1) what are the allowed line-break characters? I'd assume CR/LF as per the normal internet standard (RFC822, HTML) but that CR alone or LF alone SHOULD also be accepted.

2) what is “whitespace” (I'd assume space or tab).

3) what is “non-breaking whitespace” (I'd assume also space or tab).

The description of the keylist format in the first paragraph of 3.1 vague. Is a line with only whitespace allowed? Whitespace followed by just a comment? As written, empty lines are not allowed yet just a comment is allowed which will result in an empty line after step 1 of the fingerprint extraction process (contrary to the statement “[p]erforming these steps will result in one public key fingerprint per line”).

Perhaps some ABNF would be better even for a file as simple as this.

**Comment by milesmcc** [comment]
Thanks for this feedback. I'm working to address your comments.

One quick point regarding whitespace: it's unclear how to define it. I searched through a few RFCs, and was not able to find a precedent I could cite. [RFC 7230](https://tools.ietf.org/html/rfc7230) also mentions whitespace but does not define what it is.

Despite this precedent, it may be best to simply define whitespace as a _space_—not even a linebreak. 

As for newlines, I propose simply defining a newline as the `\n` character, that is, ASCII `NEWLINE`.

The benefits of defining a line-break as a single `\n` resolves issue 3, too, as it would refer to a specific character.

> The description of the keylist format in the first paragraph of 3.1 vague. Is a line with only whitespace allowed? Whitespace followed by just a comment? As written, empty lines are not allowed yet just a comment is allowed which will result in an empty line after step 1 of the fingerprint extraction process (contrary to the statement “[p]erforming these steps will result in one public key fingerprint per line”).

I will fix this in v02. I will mention this issue in the commit.

**Comment by milesmcc** [comment]
As for the media type, perhaps it makes sense to instead send `text/keylist;charset='utf-8'`? Because this is meant to be an Internet Standard, we could potentially propose a new media type.

**Comment by ed-davies** [comment]
Was just re-reading this and looking for useful references (such as the whitespace description in the JSON documentation) and thinking perhaps this should just be a JSON file then saw it is now. I think that's a) a good move and b) eliminates all the issues I raised originally so this issue can be closed.
