### ISSUE TITLE
Proposal: Change the format to JSON

### ISSUE THREAD

**Issue by micahflee** [firstlookmedia/keylist-rfc#8]
I like the simplicity of the current keylist format, but after some discussion with @milesmcc and @icco, I think there are some good benefits to using a more robust format that can include more data. For example, the RFC currently states:

>  To subscribe to a keylist, the client must be aware of the keylist URI (defined in [RFC3986] ), the keylist's signature URI, and the fingerprint of the authority key used to sign the keylist. 

This means that to configure a Keylist RFC client, like GPG Sync, you need to provide a fingerprint and two separate URIs. We could include the keylist's signature URI inside of the data structure, making the configuration process simpler. This won't have an affect on security because the user still provides their client the authority key fingerprint, and the signature would still need to be generated using that authority key.

Another piece of information that could be useful is a suggested keyserver to use. For example, what if an organization doesn't want to push their PGP keys to public keyservers, and instead wants everyone to use the same private keyserver?

Using a format based on JSON would also allow for more granular and parsable metadata about each key, which could be useful to any automated software that wants to work with the information in keylists. For example, each key could have a required fingerprint field, and optional name, email, and comment fields.

Also, all popular programming languages have robust JSON-parsing libraries. This would prevent the need for writing custom Keylist-parsing libraries. And like the current format, the keylist file could still be edited in a text editor by hand.

So I propose a new format, based on JSON, that looks like this:

```json
{
    "metadata": {
        "signature_uri": "https://example.com/keylist.json.asc",
        "suggested_keyserver": "hkp://keyserver.ubuntu.com",
        "comment": "This is an example of a keylist file. In the metadata section, only signature_uri is required. Both suggested_keyserver and comment are optional. And, probably suggested_keyserver could be overridden by the client."
    },
    "keys": [
        {
            "fingerprint": "927F419D7EC82C2F149C1BD1403C2657CD994F73",
            "name": "Micah Lee",
            "email": "micah.lee@theintercept.com",
            "comment": "This is what a single key in a keylist looks like. Only the fingerprint is required, but name, email, and comment might be useful too in many situations.",
        },
        {
            "fingerprint": "1326CB162C6921BF085F8459F3C78280DDBF52A1",
            "name": "R. Miles McCain",
            "email": "0@rmrm.io"
        },
        {
            "fingerprint": "E0BE0804CF04A65C1FC64CC4CAD802E066046C02",
            "name": "Nat Welch",
            "email": "nat.welch@firstlook.org"
        }
    ]
}
```

Thoughts?

If this is a good idea, are there any other pieces of information that this format should encapsulate other than what's listed above?

**Comment by icco** [comment]
Questions:

 - Should we make name optional? Do we actually need any fields besides fingerprint? Maybe make all others optional?

 - re: the following, are there any dangers here because of MITM attacks? I don't think so... but just want to make sure.
 > This won't have an affect on security because the user still provides their client the authority key fingerprint, and the signature would still need to be generated using that authority key.

 - Should we rename suggested_keyserver with keyserver ?

I think the parsing point is very good. Overall I like this.

**Comment by milesmcc** [comment]
I like the idea too. It gives us a lot more flexibility to add additional elements in the future, and also reduces the difficulty of parsing: we will simply be able to claim that the keylist must be a valid JSON dictionary with a number of required keys and cite the JSON RFC. Removes nearly all of the ambiguity of defining the actual file format specification!

**Comment by micahflee** [comment]
> Questions:
> 
> * Should we make name optional? Do we actually need any fields besides fingerprint? Maybe make all others optional?

Yes, I think everything but fingerprint should be optional.

>* re: the following, are there any dangers here because of MITM attacks? I don't think so... but just want to make sure.
> 
> > This won't have an affect on security because the user still provides their client the authority key fingerprint, and the signature would still need to be generated using that authority key.

I don't think there are any dangers, but let's think it through. The client knows the correct authority key fingerprint -- I believe this is the only piece of important information, and all other information will fail safe.

There's no reason to trust the server that hosts the keylist file. We already don't trust it -- FLM hosts our keylist on GitHub. If they chose to lock us out of our accounts and modify the content to whatever they want, they wouldn't be able make a fake keylist because they can't make a fake signature. Instead, the signature won't verify and GPG Sync will stop the process.

So if we include the signature URI in the JSON metadata, it's the same situation: another resource hosted somewhere that we don't have to trust. If an attacker could modify the keylist file to point to a malicious signature file, or if the attacker could modify the signature file, in either case they'd still need access to the authority key to generate a signature that will verify.

And if there's a MITM attack between the client and the keylist URI, or between the client and the signature URI, the attacker will still need access to the authority key to make a signature that verifies.

> * Should we rename suggested_keyserver with keyserver ?

Yes, totally.

> I think the parsing point is very good. Overall I like this.

So with these new ideas, this would be an example valid keylist:

```json
{
    "metadata": {
        "signature_uri": "https://example.com/keylist.json.asc",
        "keyserver": "hkp://keyserver.ubuntu.com"
    },
    "keys": [
        {
            "fingerprint": "927F419D7EC82C2F149C1BD1403C2657CD994F73",
            "comment": "Names and emails are optional"
        },
        {
            "fingerprint": "1326CB162C6921BF085F8459F3C78280DDBF52A1"
        },
        {
            "fingerprint": "E0BE0804CF04A65C1FC64CC4CAD802E066046C02"
        }
    ]
}
```

I think the next step is just taking a stab at writing this up in format RFC-speak.

**Comment by icco** [comment]
:+1:

**Comment by milesmcc** [comment]
@micahflee — I just did a bit of digging on HKP/HKPS, and found the following [potentially relevant citation](https://tools.ietf.org/html/rfc4387#ref-HKP) in RFC4387 (about `Internet X.509 Public Key Infrastructure Operational Protocols: Certificate Store Access via HTTP`):

> "A PGP Public Key Server", Marc Horowitz, 2000, http://www.mit.edu/afs/net.mit.edu/project/pks/thesis/paper/thesis.html.  A more complete and up-to-date overview of HKP may be obtained from the source code of an open-source OpenPGP implementation such as GPG.

The RFC also states that HKP is very undocumented, for what it's worth.

**Comment by micahflee** [comment]
Huh, who knew that HKP was barely a standard.

**Comment by wiktor-k** [comment]
> If they chose to lock us out of our accounts and modify the content to whatever they want, they wouldn't be able make a fake keylist because they can't make a fake signature. Instead, the signature won't verify and GPG Sync will stop the process.

There are two minor issues with this:

  1. malicious server could present clients old keylist file that has a valid signature (similar to replay attack). This way only fingerprints present in the first keylist file would be synced.
  2. hosting the file on foreign infrastructure has privacy problems, e.g. the operator will know IPs of people subscribed to the list (just list keyserver operators can infer keyring contents).

**Comment by micahflee** [comment]
The replay attack situation is interesting. PGP signatures are all timestamped. It would be possible for us to include in the RFC that clients should, after verifying a keylist signature, store the timestamp of the signature. If the timestamp is older than a previous stored timestamp, then reject the keylist. (On the other hand, there probably isn't much harm that could come from this replay attack. Is it worth making the RFC more complicated to prevent? Maybe we should open a separate issue to discuss...)

In terms of hosting environments, I think it's better to not define how people should host their keylists and instead keep it flexible. Many organizations (I'd guess the vast majority of them in fact, including nearly all small open source or activist communities) don't have the resources to truly control their own infrastructure. Even people who believe they're controlling their own infrastructure are normally just renting VPSes from a third party cloud provider that has the technical ability to monitor/modify it.

GPG Sync includes an option to fetch the keylist, as well as retrieve keys from the keyserver, over Tor. I think this is a better approach to solving the privacy problem, for those that want to, than trying to get everyone to purchase and maintain a physical server in a data center.

Also, this new JSON format allows keylists to provide the URIs of the signature file as well as a suggested keyserver to use. So if you're part of an org that wants to prevent any third parties from gathering IPs of your users, you could also choose to host the keylist and sig files on your own infrastructure, and get users to fetch it from your own keyserver. But otherwise, you can choose to host your keylist on Github and get users to fetch keys from the SKS pool.

**Comment by milesmcc** [comment]
The replay attack is fascinating. I'm all for adding some sort of local chronology check to the client—thought it might be best as part of a 'the client SHOULD' statement, because local storage of timestamps might significantly increase the complexity of simpler keylist client implementations. (For example, some implementations might not modify local storage at all, and simply read from some sort of configuration file to grab the keylist and sig?)

**Comment by wiktor-k** [comment]
> In terms of hosting environments, I think it's better to not define how people should host their keylists and instead keep it flexible.

Oh, I was suggesting items to put into "Security/Privacy considerations" and by no means requiring hosting the keyfile on own infrastructure :)

I've got more generic questions about the RFC and GPG Sync, would Mailing List be an appropriate place to talk?

**Comment by milesmcc** [comment]
@wiktor-k — the mailing list _would_ be a good place to talk. Glad that you're interested in the project!

**Comment by wiktor-k** [comment]
One more thing, it's rather OpenPGP trivia by why not mention it...

> This means that to configure a Keylist RFC client, like GPG Sync, you need to provide a fingerprint and two separate URIs.

It's possible to design it in a way that the *only* thing necessary would be *the fingerprint*. The rest of parameters could be embedded as signature notations on the authority key. Notations are basically metadata that can be added to any signature and they are by design signed.

For an example of this technique take a look at my key: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=vindex&search=0x653909A2F0E37C106F5FAF546C8857E0D8E8F074. `Notation data: timestamp+bitcoin-transaction@metacode.biz afcb092c5ca6409526d18ae9cf22d3b55d37e723eb1b74e3f84f7e6b052a162a` is a notation that I've added. This is as easy as running `gpg --edit-key FPR` and running `notation` subcommand. (Notation keys look like e-mails, that is to prevent collisions).

Notations can be programmatically inspected using GnuPG:

```
$ gpg --with-colons --list-options show-sig-subpackets=\"20\" --list-sigs 6C8857E0D8E8F074 | grep "^spk"
spk:20:1:114:%80%00%00%00%00*%00@timestamp+bitcoin-transaction@metacode.bizafcb092c5ca6409526d18ae9cf22d3b55d37e723eb1b74e3f84f7e6b052a162a
```

(Of course keylist would use own notation... like `keylist-url@example.com` and the value would be keylist URL)

That approach has following benefits:
  1. easy provisioning, only one parameter required,
  2. keylist URL is signed and all changes are visible on keyservers (for auditing purposes),
  3. if one refreshes the authority key before GPG Syncing it could be used to rotate keylist URL (new notations would replace old) without bothering users.

And the following disadvantages:
  1. keylist URL becomes public, may not be appropriate for people that want their keylist URLs private,
  2. a little bit of code necessary to parse GnuPG output
  3. conceptual complexity, one could be surprised where all this autoconfiguration values come from :)

**Comment by milesmcc** [comment]
@wiktor-k — that's very clever. Let's explore the idea further!

@icco @micahflee thoughts?

**Comment by micahflee** [comment]
That is clever. I see a few potential issues with it though.

There's a (potential) chicken and egg problem. The keylist can define what key server should be used, but you don't have access to that info until after you've fetched the key from a key server. So if you wanted to run a private keyserver with only your org's keys, you'll actually have to configure the client with both the fingerprint and a keyserver, not just the fingerprint. (However, nothing stops private keylists from just telling their users what keyserver to use. And if you use SKS pool or any other of the federated keyservers anyway, then it's not an issue. So maybe this isn't much of an issue.)

I've never heard of OpenPGP notation data before now. It's defined in RFC 4880 so we could rely on it, but I worry that because it's so obscure some OpenPGP implementations (like what's used in Mailvelope, ProtonMail, Canary Mail, etc.) might not have implemented it, which could make it more work for devs to adopt. (But maybe this isn't actually a problem?)

In case it is, there are other places where we can put the keylist URI. Like, what about just in the user ID packet? When generating a new key with `gpg2 --full-gen-key`, gpg asks for a comment, like:

```
GnuPG needs to construct a user ID to identify your key.

Real name: Test Keylist Authority
Email address: keylist-authority@example.com
Comment: Keylist URI: https://example.com/keylist.json
You selected this USER-ID:
    "Test Keylist Authority (Keylist URI: https://example.com/keylist.json) <keylist-authority@example.com>"
```
It looks like the OpenPGP format doesn't have a special field for comments in the uid packet, it's actually just a string. But, a keylist client could parse the string `Test Keylist Authority (Keylist URI: https://example.com/keylist.json) <keylist-authority@example.com>` to pull out `https://example.com/keylist.json`.

What if a PGP key has multiple notation data subpackets on it (or multiple user ID packets that contain the keylist URIs) -- which is the keylist client support to choose?

But in the end, I think all of the disadvantages that @wiktor-k lists maybe are a good reason to not do this. If we implement this, it's much more difficult to maintain a private keylist -- instead of just not publishing the keylist URI, you'd need to run your own private keyserver. And it does increase the complexity of this RFC, and right now I really like how simple it is. So I'm leaning towards requiring that users provide to the client both the authority key fingerprint as well as the keylist URI, at least for this first version.

**Comment by wiktor-k** [comment]
> There's a (potential) chicken and egg problem. The keylist can define what key server should be used, but you don't have access to that info until after you've fetched the key from a key server.

Hmm... good point, I forgot about that one... so... maybe use [Web Key Directory](https://metacode.biz/openpgp/web-key-directory) to pull the key and then get the keylist from that?

The user would just have to type an e-mail address like `trusted-keys@firstlookmedia.com`

> I've never heard of OpenPGP notation data before now. It's defined in RFC 4880 so we could rely on it, but I worry that because it's so obscure some OpenPGP implementations (like what's used in Mailvelope, ProtonMail, Canary Mail, etc.) might not have implemented it, which could make it more work for devs to adopt. (But maybe this isn't actually a problem?)

Mailvelope and ProtonMail both use OpenPGPjs, and OpenPGPjs is [quite feature-full](https://openpgpjs.org/openpgpjs/doc/packet_signature.js.html#line73) w.r.t. RFC 4880 support:

```js
const openpgp = require('openpgp');

new openpgp.WKD().lookup({ email: 'wiktor@metacode.biz' }).then(keys => {
    const notations = keys.keys[0].users[0].selfCertifications.pop().notation;
    console.log(notations);
}).catch(console.error.bind(console));
```

Prints:

```json
{ "timestamp+bitcoin-transaction@metacode.biz":
   "afcb092c5ca6409526d18ae9cf22d3b55d37e723eb1b74e3f84f7e6b052a162a" }
```

> It looks like the OpenPGP format doesn't have a special field for comments in the uid packet

It actually doesn't have format for the entire [UID packet](https://tools.ietf.org/html/rfc4880#section-5.11):

> By convention, it includes an RFC 2822 mail name-addr, but there are no restrictions on its content.

> What if a PGP key has multiple notation data subpackets on it (or multiple user ID packets that contain the keylist URIs) -- which is the keylist client support to choose?

Last packet from the primary User ID, that's what OpenPGPjs does by default.

> So I'm leaning towards requiring that users provide to the client both the authority key fingerprint as well as the keylist URI, at least for this first version.

Sure, as I wrote in my previous comment it's a bit of OpenPGP trivia. It can be used later or in some other solutions. In my opinion OpenPGP is full of interesting features that are unfortunately underutilized (that's in general context, not keylist per se).

**Comment by milesmcc** [comment]
> But in the end, I think all of the disadvantages that @wiktor-k lists maybe are a good reason to not do this. If we implement this, it's much more difficult to maintain a private keylist -- instead of just not publishing the keylist URI, you'd need to run your own private keyserver. And it does increase the complexity of this RFC, and right now I really like how simple it is. So I'm leaning towards requiring that users provide to the client both the authority key fingerprint as well as the keylist URI, at least for this first version.

This resonates a lot with me. The more 'magic' the system seems, the less likely people are to trust it—and even if this is an optional feature, it still greatly increases the complexity of the RFC. It's very clever, but I just worry that it'll lead to unnecessary complexity.
